#!/usr/bin/env python3
"""Combine the individual FAQ files in ``faq/`` into one page.

Each FAQ lives in its own file (``faq/<name>.md``, with ``title`` and ``tags``
in the frontmatter, and the full question as a level-2 heading). This script
writes ``faq-include.md``, which ``faq.md`` includes. The result is a single
page that has a linked list of all questions on top, followed by every
question with its tags and its full answer, so that it can be searched with
the site search, or the browser's find function.

The order of the questions is the order in which the files are listed under
``faq.md`` in ``myst.yml``. Run this before ``jupyter-book build`` (or
``jupyter-book start``) whenever FAQ files are added, removed or edited.
"""
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).parent
FAQ_DIR = HERE / "faq"
OUTPUT = HERE / "faq-include.md"


def split_frontmatter(text):
    match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not match:
        raise ValueError("missing YAML frontmatter")
    return yaml.safe_load(match.group(1)) or {}, match.group(2).strip("\n")


def toc_order():
    """FAQ files in the order listed in myst.yml."""
    text = (HERE / "myst.yml").read_text()
    return [Path(p).name for p in re.findall(r"^\s*-\s*file:\s*faq/(\S+\.md)\s*$", text, re.M)]


def main():
    on_disk = sorted(p.name for p in FAQ_DIR.glob("*.md"))
    listed = toc_order()
    unlisted = sorted(set(on_disk) - set(listed))
    missing = sorted(set(listed) - set(on_disk))
    if unlisted or missing:
        for name in unlisted:
            print(f"ERROR: faq/{name} is not listed in myst.yml", file=sys.stderr)
        for name in missing:
            print(f"ERROR: faq/{name} is listed in myst.yml but does not exist", file=sys.stderr)
        sys.exit(1)

    entries = []
    for name in listed:
        meta, body = split_frontmatter((FAQ_DIR / name).read_text())
        heading = re.match(r"^##\s+(.+?)\s*\n", body)
        if not heading:
            print(f"ERROR: faq/{name} must start with a '## Question' heading", file=sys.stderr)
            sys.exit(1)
        entries.append(
            dict(
                stem=Path(name).stem,
                title=meta.get("title", heading.group(1)),
                question=heading.group(1),
                tags=meta.get("tags") or [],
                answer=body[heading.end():].strip("\n"),
            )
        )

    out = [
        "<!-- Generated by generate_faq.py from faq/*.md -- do not edit -->",
        "",
        "## All questions",
        "",
    ]
    out += [f"- [{e['question']}](#faq-{e['stem']})" for e in entries]
    out.append("")
    for e in entries:
        out += [f"(faq-{e['stem']})=", f"## {e['question']}", ""]
        if e["tags"]:
            out += ["*Tags: " + " · ".join(str(t) for t in e["tags"]) + "*", ""]
        out += [f"[Link to this question on its own page](faq/{e['stem']})", "", e["answer"], ""]
    OUTPUT.write_text("\n".join(out))
    print(f"Wrote {OUTPUT.name} with {len(entries)} FAQ entries")


if __name__ == "__main__":
    main()
