name: Quarto Render and Deploy to GitHub Pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to GitHub Pages'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

# Ensure GitHub Pages settings for this repository are set to deploy with GitHub Actions.
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render site
        run: quarto render website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website/_site'

  deploy:
    needs: build
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && inputs.deploy == 'true')
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
